
# Name your project! Project names should be lowercase and use underscores as spaces.
name: 'crime_analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'crime_analytics'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  crime_analytics:
    staging:
      +materialized: table
      +schema: staging
    marts:
      +materialized: table
      +schema: mart

vars:
  start_date: '2026-01-01'
